export interface IProduct {
    group: string;
    tag: string;
    image: string;
    createdAt?: string; // timestamps are optional because they are auto-generated by Mongoose
    updatedAt?: string;
    _id : string,
}
  